KWBlogg/Controllers/BlogPostsController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KWBlogg.Helpers;
using KWBlogg.Models;
using static KWBlogg.Helpers.StringUtilites;

namespace KWBlogg.Controllers
{
    
    public class BlogPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BlogPosts
        public ActionResult Fetured()
        {
            return View(db.Posts.OrderByDescending(p => p.Created).FirstOrDefault());
            //return View(db.Posts.Where(b => b.Published));
        }

        // GET: BlogPosts/Details/5

        public ActionResult Details(string Slug)
        {
            if (String.IsNullOrWhiteSpace(Slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.FirstOrDefault(p => p.Slug == Slug);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        [Authorize(Roles = "Admin")]
       
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    BlogPost blogPost = db.Posts.Find(id);
        //    if (blogPost == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(blogPost);
        //}

        // GET: BlogPosts/Create
        public ActionResult Create()
        {



            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create([Bind(Include = "Id,Title,Body,MediaURL,Published")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {

                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.MediaURL = "/Uploads/" + fileName;
                    
                }

                var Slug = StringUtilities.URLFriendly(blogPost.Title);

                if (String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid title");
                    return View(blogPost);
                }
                if (db.Posts.Any(p => p.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "The title must be unique");
                    return View(blogPost);
                }

                blogPost.Slug = Slug;
                blogPost.Created = DateTimeOffset.Now;
                db.Posts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Fetured");
            }

            return View(blogPost);
        }


        //public ActionResult Create([Bind(Include = "Title,Abstract,Body,MediaURL,Published")] BlogPost blogPost)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        blogPost.Created = DateTimeOffset.Now;
        //        db.Posts.Add(blogPost);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(blogPost);
        //}

        // GET: BlogPosts/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Created,Updated,Title,Slug,Body,MediaURL,Published")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads"), fileName));
                    blogPost.MediaURL = "/Uploads/" + fileName;

                }

                var slug = StringUtilities.URLFriendly(blogPost.Title);
                if (blogPost.Slug != slug)
                {
                    if (String.IsNullOrWhiteSpace(slug))
                    {
                        ModelState.AddModelError("Title", "Invalid title");
                        return View(blogPost);
                    }

                    if(db.Posts.Any(p => p.Slug == slug))
                    {
                        ModelState.AddModelError("Title", "The title must be unique");
                        return View(blogPost);
                    }
                    blogPost.Slug = slug;
                }

                blogPost.Updated = DateTimeOffset.Now;
                db.Entry(blogPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Fetured");
            }
            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.Posts.Find(id);
            db.Posts.Remove(blogPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult BlogPost()
        {
            return View();
        }


        public ActionResult BlogPosts()
        {
            return View(db.Posts.Where(p => p.Published).ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KWBlogg/Controllers/HomeController.cs
using KWBlogg.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace KWBlogg.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Contact(/*EmailModel email*/)
        {
            EmailModel model = new EmailModel();
            return View(model);
            //return RedirectToAction("Index");
        }
        public async Task<ActionResult> Contact(EmailModel email)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var from = $"{email.FromEmail}<{WebConfigurationManager.AppSettings["emailfrom"]}>";
                    var emailMessage = new MailMessage(from, ConfigurationManager.AppSettings["emailto"])

                    {
                        Subject = email.Subject,
                        Body = email.Body,
                        //IsBodyHtml = true
                    };

                    var svc = new PersonalEmail();
                    await svc.SendAsync(emailMessage);

                    //return View(new EmailModel());
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    await Task.FromResult(0);
                }
                }

                return View();

            
        }
    }
}

KWBlogg/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

KWBlogg/Views/Home/Contact.cshtml
@model KWBlogg.Models.EmailModel



<section id="content">
    <iframe src="https://maps.google.com/maps?q=kernersvile%2C%20nc&t=&z=13&ie=UTF8&iwloc=&output=embed" width="100%" height="380" frameborder="0" style="border:0" allowfullscreen> ></iframe>
    <div class="container">
        <div class="row">
            <div class="span8">



                <h4>Get in touch with me by filling the contact form below</h4>
                <hr />

                <div id="sendmessage">Your message has been sent. Thank you!</div>
                <div id="errormessage"></div>

                @using (Html.BeginForm())
                {

                    @Html.AntiForgeryToken()

                    <div class="row">
                        <div class="span4 form-group field">
                            <input type="text" name="FromName" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                            <div class="validation"></div>
                        </div>

                        <div class="span4 form-group">
                            <input type="email" name="FromEmail" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                            <div class="validation"></div>
                        </div>
                        <div class="span8 form-group">
                            <input type="text" name="Subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                            <div class="validation"></div>
                        </div>
                        <div class="span8 form-group">
                            <textarea name="Body" rows="5" data-rule="required" data-msg="Please write something for us"
                                      placeholder="Write Message Here"></textarea>
                            <div class="validation"></div>
                            <div class="text-center">
                                <button class="btn btn-theme btn-medium margintop10" type="submit">Send a message</button>
                            </div>
                        </div>
                    </div>

                }
            </div>
            <div class="span4">
                <div class="clearfix"></div>
                <aside class="right-sidebar">

                    <div class="widget">
                        <h5 class="widgetheading">Contact information<span></span></h5>

                        <ul class="contact-info">
                            <li><label>Address :</label>1231 Shields Rd #5<br />Kernersville, NC 27284</li>
                            <li><label>Phone :</label>(336) 231-8632</li>
                            <li><label>Email : </label> info@coderfoundry.com</li>
                        </ul>

                    </div>
                </aside>
            </div>
        </div>
    </div>
</section>


<a href="#" class="scrollup"><i class="icon-angle-up icon-square icon-bglight icon-2x active"></i></a>

KWBlogg/Views/Home/Index.cshtml
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

@Html.ActionLink("Enter", "Fetured", "BlogPosts", null, new { @class="classname" })